// flow-typed signature: 36479ba492b1f4afa6200f8ad4a02197
// flow-typed version: <<STUB>>/accept-language_v^3.0.17/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'accept-language'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'accept-language' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'accept-language/Build/Source/AcceptLanguage' {
  declare module.exports: any;
}

// Filename aliases
declare module 'accept-language/Build/Source/AcceptLanguage.js' {
  declare module.exports: $Exports<'accept-language/Build/Source/AcceptLanguage'>;
}
