// flow-typed signature: 9f195ad121e9306768f44a4d969c31dd
// flow-typed version: <<STUB>>/message-format_v^5.1.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'message-format'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'message-format' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'message-format/index' {
  declare module.exports: $Exports<'message-format'>;
}
declare module 'message-format/index.js' {
  declare module.exports: $Exports<'message-format'>;
}
