// flow-typed signature: 6d3ee3416821ff213203a3b053bf6821
// flow-typed version: <<STUB>>/simple-webpack-progress-plugin_v^1.0.4/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'simple-webpack-progress-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'simple-webpack-progress-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'simple-webpack-progress-plugin/index' {
  declare module.exports: $Exports<'simple-webpack-progress-plugin'>;
}
declare module 'simple-webpack-progress-plugin/index.js' {
  declare module.exports: $Exports<'simple-webpack-progress-plugin'>;
}
